### ISSUE TITLE
prb: last activation

### ISSUE THREAD

**Issue by bozgrind** [0brz/parcel#19]
## maybe sol: 
add ring list to `re-activate` hard logic stucture under list/set collections

### problem example
```
    list:
        vector:
            set:
                - a
                - b

            "some_delimiter"
            
            set:  (problem last collection tag)
                - A
                - B 
```

```
    source = {
        "a",
        "a",
        "b",
        "B",
        "<>",
        "a",
        "B",
        "A",
        "<>",
        "a",
        "B",
        "A"
    };
```
when cursor step on last vector tag (set), we can't re-build this structure from begin
